<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Ip Contact Groups' => 'Создать группу контактов',
    'Ip Contact Groups' => 'Группы контактов',
    'Ip Contact ID' => 'Контакт',
    'Update Ip Contact' => 'Обновить контакт',
    'Update Ip Contact Group' => 'Обновить группу контактов',
    'Create Ip Contact' => 'Создать контакт',
    'Ip Contact Groups ID' => 'Группа',
    'Ip Contact Groups Name' => 'Группа',
    'Ip Contact Name' => 'Имя',
    'Ip Contact Phone' => 'Телефон',
    'Ip Contacts' => 'Контакты IP телефонии',
];