<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Config Ofoms Url Prik' => 'Ссылка для прикрепления пациентов на портале ОФОМС',
    'Connection Error' => 'Ошибка соединения',
    'Connection Error With OFOMS' => 'Ошибка соединения с порталом ОФОМС',
    'List File' => '',
    'Upload List' => 'Загрузить список пациентов',
    'Attach' => 'Прикрепить пациента',
    'Attach with list' => 'Прикрепление списком',
    'Attached' => 'Прикреплен',
    'Close' => 'Закрыть',
    'Config Ofoms Active' => 'Активировать портал "ОФОМС"',
    'Config Ofoms Login' => 'Логин портала ОФОМС',
    'Config Ofoms Password' => 'Пароль портала ОФОМС',
    'Config Ofoms Remote Host Name' => 'Хост портала ОФОМС',
    'Config Ofoms Url' => 'Ссылка для проверки полисов на портале ОФОМС',
    'Don\'t attached to LPU' => 'Не прикреплен к ЛПУ',
    'Non Attached' => 'Не прикреплен',
    'Ofoms search' => 'Поиск',
    'Ofoms search rules' => 'Правила поиска',
    'Removed' => 'Снят с учета',
    'Rules' => 'Правила поиска',
    'Search' => 'Поиск',
    'Type to search input and press Enter button' => 'Введите строку поиска и нажмите клавишу Enter на клавиатуре',
    'Vrach' => 'Врач',
    'Ofoms Portal' => 'Портал проверки полисов пациентов ОФОМС',
];
