<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Update Tiles' => 'Обновить плитку на главной странице',
    'Update "{modelClass}": ' => '@@@@',
    'Choose Icon' => 'Выберите иконку превью',
    'Close' => 'Закрыть',
    'Create Tiles' => 'Добавить плитку на главной странице',
    'Crop' => 'Обрезать',
    'Cropper dialog' => 'Обрезать картинку',
    'Icon' => 'Иконка',
    'Picture' => 'Картинка',
    'Preview' => 'Превью',
    'Tiles' => 'Плитки на главной странице',
    'Tiles Description' => 'Описание',
    'Tiles Icon' => 'Иконка',
    'Tiles Icon Color' => 'Стиль превью',
    'Tiles Keywords' => 'Ключевые слова для поиска',
    'Tiles Link' => 'Ссылка',
    'Tiles Name' => 'Название',
    'Tiles Thumbnail' => 'Превью',
    'Upload Image' => 'Загрузить картинку',
];
